### ISSUE TITLE
Access to azure pipeline

### ISSUE THREAD

**Issue by tomaszduda23** [home-assistant/docker#101]
Hi,

When I try to access azure pipeline I got 401 - Uh-oh, you do not have access.
I'm not experience with azure but it seems that project is private.
It would be useful if ever one can get read only access.

BR,
TD

**Comment by pvizeli** [comment]
That is a local issue with your refresh token. It runs in the same namespace as all other pipelines: https://dev.azure.com/home-assistant/Supervisor/_build
