### ISSUE TITLE
failed to pull last image: too many levels of symbolic links

### ISSUE THREAD

**Issue by magostinelli** [home-assistant/docker#108]
If I update via supervisor (hass.io) it gives me a 404.
So, i tryed to pull image manually, and I get the following error:
docker pull homeassistant/raspberrypi4-homeassistant:0.107.7
.
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/cf7d66980d33c962fd2f859133d097897219d3e71ec4788e2c3a17f5155242d1/merged: too many levels of symbolic links

**Comment by pvizeli** [comment]
`ha su repair` fix the issue, maybe it need also a reboot if that is finish. Do you use Home Assistant OS? They should be optimized to have no such issue normally

**Comment by magostinelli** [comment]
I don't have hass os, I have a raspbian, where I installed the hassio-supervisor, so there is no ha command to launch.

**Comment by pvizeli** [comment]
use the terminal add-on.

**Comment by magostinelli** [comment]
Already installed, tryed the command, but the error still remain.

I tryed to pull the dev image, and it works without issue.

**Comment by larcher** [comment]
I'm seeing the same, on a fresh install using Hass OS (following the [installation instructions](https://www.home-assistant.io/hassio/installation/)).  
I did try doing `ha su repair` and then a reboot, but no luck. 

I got the error when trying to pull `0.108.6`, which it was failing to install during the first update.  Also tried pulling some other tags (`0.108.5`, `0.108.0`, `latest`, `stable`, `dev`), all failed the same way.  

In case it helps, here's a failing docker pull 
```
# docker pull homeassistant/raspberrypi4-homeassistant:latest
latest: Pulling from homeassistant/raspberrypi4-homeassistant
d9bf605ce3d4: Already exists
dd5dc70596bc: Already exists
49ac754657d1: Already exists
b0e4c16b0ca8: Extracting [==================================================>]  45.38kB/45.38kB
315798b43a42: Download complete
a9efeae62a42: Download complete
8c0b90199c2d: Download complete
712b32cd1982: Download complete
9cd68924c946: Download complete
e1b1ff1b5e1e: Download complete
c0c8837b44dd: Download complete
194f248983a0: Download complete
6a986aabf039: Download complete
23d0d94d2169: Download complete
6d534efa0401: Download complete
05dfb277c68d: Download complete
02474b35a623: Download complete
c116d2e97ef0: Download complete
cd0d88e85a89: Download complete                                                                                                                                                                                 298bb3dbb19a: Download complete
337e1feb2ccb: Download complete
f20304801786: Download complete
5165bf6848c6: Download complete
eceac4c4e8b5: Download complete
9f03f5fd5477: Download complete
failed to register layer: error creating overlay mount to /mnt/data/docker/overlay2/12b6d6f6e9d6ce1daa6e857079e501f78e75ce65bd1dc5ae2f1714e7242b04d3/merged: too many levels of symbolic links
```
Always seems to fail on that one layer, `b0e4c16b0ca8`

**Comment by larcher** [comment]
Looks like there's more discussion of the problem over at https://github.com/home-assistant/supervisor/issues/1506

**Comment by too-far-away** [comment]
I'm observing the same issue with `homeassistant/raspberrypi3-homeassistant:0.118.5` image (actually happened also to 0.118.3 and 0.118.4).
Docker version 19.03.14 (the latest available with apt)

**Comment by luizbalestreri** [comment]
i'm also having this problem on raspberry pi 3
