### ISSUE TITLE
failed to download from docker:  too many levels of symbolic links

### ISSUE THREAD

**Issue by magostinelli** [home-assistant/docker#111]
If I update via supervisor (hass.io) it gives me a 404.
So, i tryed to pull image manually, and I get the following error:
docker pull homeassistant/raspberrypi4-homeassistant:0.107.7
.
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/cf7d66980d33c962fd2f859133d097897219d3e71ec4788e2c3a17f5155242d1/merged: too many levels of symbolic links

Also tryed without success:
ha su repair

Already rebooted the system.

If I pull the dev image it works.

**Comment by pvizeli** [comment]
Which version of Home Assistant OS do you run?

**Comment by magostinelli** [comment]
I run raspbian (Raspbian GNU/Linux 10 buster), i followed the guide on hass.io:
https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host

**Comment by frenck** [comment]
Are you using remotely mounted partitions?

**Comment by magostinelli** [comment]
No, i have only an usb drive mounted.

**Comment by frenck** [comment]
Ok, sorry for the questions, I'm just looking for possible issues. It the /var/lib/docker folder mounted on a different device, and if so, which file system is running on it?

**Comment by magostinelli** [comment]
No, problem, ask everything you need, I appreciate your help.
The filesystem is ext4 and /var/lib/docker is on the / partition:

NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    1 114,6G  0 disk
└─sda1        8:1    1 114,6G  0 part /mnt/usb
mmcblk0     179:0    0 119,1G  0 disk
├─mmcblk0p1 179:1    0   256M  0 part /boot
└─mmcblk0p2 179:2    0 118,9G  0 part /

Thank you.

**Comment by magostinelli** [comment]
Hello, anyone can help me?
I have tryed too many times to update without success.

Thanks.
