### ISSUE TITLE
picotts native library is missing from base image

### ISSUE THREAD

**Issue by kngharv** [home-assistant/docker#114]
picotts component require an OS-level library which is missing from the docker base image (as of version 0.108.1).

While the library doesn't exist in 3.11 repository, picotts does exist at the testing/edge repository.

Since picotts is a very mature library and the picotts code itself hasn't changed for years,  it should be stable enough to be incorporate into the docker base image without much ill effect.

The library has been compiled and packaged for various distribution AND x86-32/64/ARM machine architectures.

All we have to do is include add a single line at the Dockerfile in the `Install component packages` section:

`
RUN apk add --no-cache picotts --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing`

By including picotts into the docker base image,  Home Assistant will have built-in TTS solution right out of the box with truly bare minimum configurations.

**Comment by maxfarrior** [comment]
I want to bring attention to this.

Having a **local** TTS option would be a worthy inclusion into Home Assistant.

I just moved HA into Docker, and I've lost the ability to use PicoTTS.

I'd like to reference [Issue #24749 of home-assistant/core](https://github.com/home-assistant/core/issues/24749) as well as [Poeschl/Remote-PicoTTS](https://github.com/Poeschl/Remote-PicoTTS).
