### ISSUE TITLE
Request: Tag with version number for patch releases

### ISSUE THREAD

**Issue by ronaldheft** [home-assistant/docker#116]
Since Home Assistant has moved to releasing more patch updates, and versions have started including lots of breaking changes due to YAML migrations, could we start tagging patch release versions with the main version number?

Right now, I’m specifying my Docker tags to pull `stable`, but I would love to be able to specify the version number, ex. `0.109`. That way, I could have my auto-update scripts keep my Home Assistant up to date without fear of installing a breaking change. Then when I get time, usually on weekends, I could bump my script to the next version, ex. `0.110`, and go through the breaking changes.

Thoughts?

**Comment by frenck** [comment]
If you use a script to update already, why not make it check which releases are available and implement this part yourself?

**Comment by ronaldheft** [comment]
Good call @frenck.

For anyone who stumbles on this request in the future, here is the script I wrote (uses a text file `ha-version-allowed.txt` to determine what is safe to update):

```
#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo "Validating current HomeAssistant version..."

echo ""

export PYTHONIOENCODING=utf8
ALLOWED_VERSION=$(<${DIR}/ha-version-allowed.txt)
HA_VERSION=$(curl -s 'https://updater.home-assistant.io' | python2 -c "import sys, json; print json.load(sys.stdin)['version']")
echo "Allowed Version: ${ALLOWED_VERSION}"
echo "Lastest Version: ${HA_VERSION}"

echo ""

if [[ $HA_VERSION == $ALLOWED_VERSION* ]]
then
	echo "Updating HomeAssistant and related Docker containers..."
	exec /volume1/docker/run-docker-compose.sh ha
else
	echo "New major version of HomeAssistant! Verify release notes and modify ha-allowed-version.txt when ready to update."
fi

exit 0
```

Output when safe to update:

```
Validating current HomeAssistant version...

Allowed Version: 0.109
Lastest Version: 0.109.3

Updating HomeAssistant and related Docker containers...
```

Output when version changes:

```
Validating current HomeAssistant version...

Allowed Version: 0.108
Lastest Version: 0.109.3

New major version of HomeAssistant! Verify release notes and modify ha-allowed-version.txt when ready to update.
```

**Comment by frenck** [comment]
Better to use this one: <https://version.home-assistant.io/stable.json>

It contains more architecture information and is updated on release automatically.

**Comment by ronaldheft** [comment]
Thanks! Updated my script to use that URL instead.

**Comment by frenck** [comment]
👍 
I'm closing this for now. I think this becomes more relevant as we pass on to 1.0.

**Comment by lalexdotcom** [comment]
Great script ronaldheft, thanks for sharing!

Whatever, tagging the way you talked about is a very common thing in docker hub...
Most big projects have this king of tags: 
- python has 3.8.2-buster, 3.8-buster, 3-buster, buster
- mysql has 8.0.20, 8.0, 8, latest
etc...

It's more secure for the stability of a docker stack as it allows to have the latest security updates by fixing a version without introducing breaking changes...

**Comment by jschlyter** [comment]
@frenck Now that we are passed "1.0", perhaps it is time to start tagging the latest release of each month? (e.g., `:2021:4`)
This would help people tracking a specific release a lot.

**Comment by frenck** [comment]
@jschlyter We are on the verge of changing our build system, after that we can look into it. 👍
