### ISSUE TITLE
Image started failing on Fedora 32 since homeassistant/home-assistant:0.107.0

### ISSUE THREAD

**Issue by paoloantinori** [home-assistant/docker#118]
Some change occurred between `homeassistant/home-assistant:0.106.0`  and `homeassistant/home-assistant:0.107.0`  breaks the behavior on Fedora32 `x86_64`.

I've filed a bug report against `podman` but I'm not sure if the problem is on this or their side, considering that `0.106.0` starts up fine.

https://github.com/containers/libpod/issues/6185

https://gist.github.com/paoloantinori/94ef7334005f8efd650180570cc1c490

The issue might be in the base image though:

`homeassistant/i386-base-python:3.7-alpine3.11` throws the same exact error.

**Comment by frenck** [comment]
Hi there, thanks for opening up an issue.

Unfortunately, we currently don't support podman. It might be caused by the rootless nature.

I hope you'll find an answer to your issue. 👍
