### ISSUE TITLE
Incoming SMS notification are broken in Gammu 1.41

### ISSUE THREAD

**Issue by ocalvo** [home-assistant/docker#119]
The current version of Gammu 1.41 have an [active issue](https://github.com/gammu/gammu/issues/460) that prevent incoming SMS to work.
While we wait for a fix, can we downgrade the version used in the Docker to version 1.39 (LKG)

**Comment by tiagofreire-pt** [comment]
@ocalvo , could you check if changing the requirement here is enough?

https://github.com/home-assistant/core/blob/dev/homeassistant/components/sms/manifest.json

**Comment by ocalvo** [comment]
We need to change the version of lib-gammu to version 0.39 [here](https://github.com/home-assistant/docker/blob/907556b6f8784e34c8c6e2a88f8853f2bad0f379/base/Dockerfile#L37)

**Comment by pvizeli** [comment]
We can not downgrade. You need open an issue by Alpine and ask for an upgrade - better is to fix the issue on Alpine packages

**Comment by tiagofreire-pt** [comment]
> 
> 
> We can not downgrade. You need open an issue by Alpine and ask for an upgrade - better is to fix the issue on Alpine packages

It seems that we can stick to a particular package version:

```
##
# Install component packages
RUN apk add --no-cache \
    bluez \
    bluez-deprecated \
    bluez-libs \
    cups-libs \
    curl \
    ffmpeg \
    ffmpeg-libs \
    freetds \
    gammu-libs=1.39.0-r2 \
    git \
    glib \
    gmp \
    iperf3 \
    libsodium \
    libwebp \
    libxml2 \
    libxslt \
    mariadb-connector-c \
    mpc1 \
    mpfr4 \
    net-tools \
    nmap \
    openssh-client \
    pianobar \
    postgresql-libs \
    pulseaudio-utils \
    socat \
    unixodbc \
    zlib
```

Don't we, @pvizeli ?

**Comment by PaulAnnekov** [comment]
@tiagofreire-pt I will answer your question. No, it's not possible with Alpine, their repositories contain only single version. 
Actually, Alpine 3.13 already contains fixed gammu-libs version.
