### ISSUE TITLE
Outdated pianobar version

### ISSUE THREAD

**Issue by cithraul** [home-assistant/docker#126]
The version of Pianobar included in the docker version of home assistant is outdated. Can it please be updated to the latest version? The latest version supports audio pipes, as well as custom sample rates and fixes an issue with Pandora where only 95 stations are available.

**Comment by ludeeus** [comment]
In 0.113.0 (current beta) this is now version `2020.04.05-r1` which is the newest available version of it for Alpine 3.12.
<https://pkgs.alpinelinux.org/packages?name=pianobar&branch=v3.12>
