### ISSUE TITLE
homeassistant/home-assistant:0.112.5 missing

### ISSUE THREAD

**Issue by baurmatt** [home-assistant/docker#129]
0.112.5 got [released](https://github.com/home-assistant/core/releases/tag/0.112.5) two weeks ago but I can't find the release on Docker Hub

**Comment by pvizeli** [comment]
It's never released on docker

**Comment by baurmatt** [comment]
Shouldn't every release of Home Assistant Core be released as Docker image?

**Comment by frenck** [comment]
@baurmatt Normally, yes. It was the original intention of having it available. However, due to a conflict with the 0.113 release, the builds failed.

Fixing that for a patch release was considered too risky.
