### ISSUE TITLE
run as non-root user

### ISSUE THREAD

**Issue by DarkPark** [home-assistant/docker#140]
For isolation and better protection I'm running all my docker containers with non-root user permissions.
I'd like to be able to do the same with home-assistant:

```
docker run \
	--init \
	--detach \
	--user 1011:1011 \
	--restart unless-stopped \
	--device /dev/snd \
	--device /dev/ttyUSB.RS485 \
	--volume /home/docker/home-assistant/config:/config \
	--env "TZ=Europe/Kiev" \
	--net host \
	--name home-assistant \
	homeassistant/home-assistant:stable
```

but get this log:

```
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

Can you please improve your image to support this approach?

**Comment by ludeeus** [comment]
<https://github.com/home-assistant/architecture/blob/master/adr/0013-home-assistant-container.md#decision>

> The only supported way to run the container is on the host network as root with full privileges.

Running as root is a requirement, this is not an issue, for feature requests use [our forum](https://community.home-assistant.io/c/feature-requests/13)

**Comment by DarkPark** [comment]
grafana, mosquitto, nginx, node-red, pihole, prometheus, zigbee2mqtt and so on
all these images can be used without root privileges
why do you need these permissions?
with `--net host` you have full access to the network, config dir is writable
so what else?

**Comment by pvizeli** [comment]
You looking for: https://github.com/tribut/homeassistant-docker-venv
