### ISSUE TITLE
Unable to build HA Image

### ISSUE THREAD

**Issue by AdvaitT17** [home-assistant/docker#141]
I am newb to docker. I was trying to run home assistant core. I used docker save command to clone ha core image and after making some changes in layer.tar files, I ran docker load to see if the changes were live...though got errors on startup.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] udev.sh: executing...

starting version 3.2.9

[23:15:11] INFO: Update udev information

[cont-init.d] udev.sh: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

/usr/local/bin/python3: No module named homeassistant

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

**Comment by pvizeli** [comment]
https://www.home-assistant.io/help/
