### ISSUE TITLE
Request: Smaller Images

### ISSUE THREAD

**Issue by megusta-01** [home-assistant/docker#166]
Hi,
is it possible to make docker images smaller or make hass modular?
My guess is that hass installed all modules of listed devices. Why do I need them all? The list grows every day, in few years you've to download 10GB ?
It would be enough if I just see the headline after a configuration and the rest will be downloaded bit by bit.

This is not a criticism only a suggestion. I know you've enough other stuff to do

**Comment by pvizeli** [comment]
Feature request into forum please
