### ISSUE TITLE
Wake on lan not working on Pi 4 in Docker with Pi 4 image

### ISSUE THREAD

**Issue by aukedejong** [home-assistant/docker#169]
Wake on lan is not working on with version: Home Assistant 2021.3.1 running on Docker on a Pi 4.
Wol is working on the same version on a Raspberry Pi 3.

My analysis:
[https://community.home-assistant.io/t/wake-on-lan-not-working-from-ha-running-in-pi4-docker-container-found-problem-in-python-code/289386](https://community.home-assistant.io/t/wake-on-lan-not-working-from-ha-running-in-pi4-docker-container-found-problem-in-python-code/289386)

Finally a Python code change fixed it, but I don't understand why.
And I don't want to change the code every time I update HA or restart the container.

Is it OK to point to a forum post?
Also, I'm not sure this is the right place for the issue.

**Comment by frenck** [comment]
I'm not sure, are you reporting an issue with a Home Assistant integration in this case?

**Comment by aukedejong** [comment]
It's an issue with the Wake On Lan integration, but only on Pi 4 in a docker container. (as far as I know)

I added the link to the forum post above.

**Comment by frenck** [comment]
So, integration issues should be reported here:

<https://github.com/home-assistant/core/issues>

Thanks already! 👍
