### ISSUE TITLE
Need ability to use socat in home assistant docker

### ISSUE THREAD

**Issue by foxy82** [home-assistant/docker#92]
**Home Assistant release with the issue:**

hassio version 195

**Operating environment (HassOS/Generic):**

hassio_Supervisor / homeassistant running in docker

**Description of problem:**

Whilst socat is installed in homeassistant docker image there is no obvious way to use this on an on-going basis. Can we add the ability to configure socat ports so that they are created on startup.

**Comment by foxy82** [comment]
I have a serial device on another computer that I expose via ser2net. I then want to connect to this device in home assistant docker using a /dev/ser2netDevice link.

I tried running socat locally but the pyudev library doesn't see the socat device so doesn't pass it through to the home assistant docker

**Comment by foxy82** [comment]
Similar to the way zigbee2mqtt provides this in its add-on. However it isn't a ZigBee or zwave stick I want this to work with.

**Comment by Hedda** [comment]
Would this maybe be better served as a seperate add-on for HASSIO on its own?

- https://www.home-assistant.io/addons/
- https://github.com/hassio-addons

That is, if socat was its own HASSIO addon could it be used to connect remotely to all types of serial/UART based RF-adapters and presented as TTY serial port to the OS / Home Assistant? 

- https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

If I understand correctly that could in theory then work with all ser2net served adapters no matter if it is Zigbee, Z-Wave, other RF, or just a standard com-port as long as its serial and low-bandwidth?

**Comment by pvizeli** [comment]
I would suggest to extend the Hardware API and Supervisor to connect and handle serial devices over TCP and map this to add-ons or Home Assistant.
