### ISSUE TITLE
IPv6 in Docker Container

### ISSUE THREAD

**Issue by demonspork** [home-assistant/docker#97]
Currently using Unraid 6.8 with working ipv6 in all other docker containers. Ipv6 is not working in the Home-Assistant Docker container, I have even updated to latest. The container shows the ipv6 address as assigned in "docker inspect" but it is not able to reach out when using the curl test on [this page](https://companion.home-assistant.io/docs/troubleshooting/errors) or browsing directly via the IPv6 address. The output of ip address also shows the ipv6 address assigned.

**Comment by frenck** [comment]
You can configure the Home Assistant core to either listen on IPv4 or IPv6 (not both).

<https://www.home-assistant.io/integrations/http/#server_host>

The default is that Home Assistant listens to IPv4 only.

If you need/require both to be active at the same time, the use of a reverse proxy is advised.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/supervisor/issues/1405
