### ISSUE TITLE
old python3 pkg rocketchat_API

### ISSUE THREAD

**Issue by nickma82** [home-assistant/docker#99]
Hi,
I think I finally found the problem of my constant `Rocket.Chat authentication failed for user <some@user.at>` problem, with the [rocketchat integration](https://www.home-assistant.io/integrations/rocketchat/).
Namely an old python3 rocketchat_API version (rocketchat-API==0.6.1) inside the current docker container (v 3.2.8).

# Problem
I receive the following error while using the `homeassistant/home-assistant` container, which I'm able to reproduce locally if I'm installing `pip3 install rocketchat_API=0.6.1`.
```
# docker image rocketchat_API==0.6.1
$ docker run --rm homeassistant/home-assistant pip3 freeze|grep rocket                                                                                                                    
starting version 3.2.8
rocketchat-API==0.6.1

$ docker run --rm homeassistant/home-assistant python3 -c "from rocketchat_API.rocketchat import RocketChat; r=RocketChat('some@user.at', 'some_password', server_url='https://open.rocket.chat');r.chat_post_message('test2', channel='test_channel')"
starting version 3.2.8
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/rocketchat_API/rocketchat.py", line 19, in __init__
    self.login(user, password)
  File "/usr/local/lib/python3.7/site-packages/rocketchat_API/rocketchat.py", line 60, in login
    raise RocketAuthenticationException()
rocketchat_API.APIExceptions.RocketExceptions.RocketAuthenticationException
```
Issuing the [Rocket.Chat authentication failed](https://github.com/home-assistant/core/blob/dev/homeassistant/components/rocketchat/notify.py#L46) log warning.

## Problematic HassIO version
```
$ ha info
arch: aarch64
channel: stable
hassos: "3.12"
homeassistant: 0.106.5
hostname: homeassistant
logging: info
machine: raspberrypi3-64
supervisor: "209"
```

# Suggested Fix
Update to python3 package `rocketchat_API==1.1.0` (which I dont know how to do?)
## testing 
The following works for me
```
$ pip3 freeze|grep rocket
rocketchat-API==1.1.0
$ python3 -c "from rocketchat_API.rocketchat import RocketChat; r=RocketChat('some@user.at', 'some_password', server_url='https://open.rocket.chat');r.chat_post_message('test2', channel='test_channel')"
```

Best, Nick

**Comment by frenck** [comment]
Hi there, thanks for opening up an issue.

The dependencies for Home Assistant Core, are defined in the integrations inside Home Assistant Core itself and are not part of our Docker images configuration/setup.

If you have an issue with one of the Home Assistant integrations, please raise an issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

**Comment by nickma82** [comment]
Perfect, thanks.
Best, Nick
